-- MySQL Script generated by MySQL Workbench
-- Thu May 28 00:18:46 2015
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema PurpleDatabase
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `PurpleDatabase` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `PurpleDatabase` ;

-- -----------------------------------------------------
-- Table `PurpleDatabase`.`database`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PurpleDatabase`.`database` ;

CREATE TABLE IF NOT EXISTS `PurpleDatabase`.`database` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `version` VARCHAR(45) NOT NULL,
  `valid_from` TIMESTAMP NULL,
  `timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `PurpleDatabase`.`database`
-- -----------------------------------------------------
START TRANSACTION;
USE `PurpleDatabase`;
INSERT INTO `PurpleDatabase`.`database` (`id`, `version`, `valid_from`, `timestamp`) VALUES (1, '0.0.0.0', '2015-05-27 23:58:17', '2015-05-27 23:58:17');
INSERT INTO `PurpleDatabase`.`database` (`id`, `version`, `valid_from`, `timestamp`) VALUES (2, '0.0.1.0', '2015-05-28 00:01:17', '2015-05-28 00:01:17');

COMMIT;

