-- MySQL Script generated by MySQL Workbench
-- Fri Mar  6 22:44:13 2015
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema PurpleDatabase
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `PurpleDatabase` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `PurpleDatabase` ;

-- -----------------------------------------------------
-- Table `PurpleDatabase`.`account_log`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PurpleDatabase`.`account_log` ;

CREATE TABLE IF NOT EXISTS `PurpleDatabase`.`account_log` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'Table with all important account related log entries',
  `account_id` INT NOT NULL,
  `log` TEXT NULL,
  `timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `account_id_id1` (`account_id` ASC),
  CONSTRAINT `account_log_1`
    FOREIGN KEY (`account_id`)
    REFERENCES `PurpleDatabase`.`account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
