-- MySQL Script generated by MySQL Workbench
-- Wed Feb 25 23:11:22 2015
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema PurpleDatabase
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `PurpleDatabase` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `PurpleDatabase` ;

-- -----------------------------------------------------
-- Table `PurpleDatabase`.`account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PurpleDatabase`.`account` ;

CREATE TABLE IF NOT EXISTS `PurpleDatabase`.`account` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'Main user account',
  `GUID` VARCHAR(45) NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(60) NOT NULL,
  `account_type` ENUM('User', 'Moderator', 'GameMaster', 'Monitoring') NOT NULL DEFAULT 'User',
  `email` VARCHAR(100) NOT NULL,
  `email_verification` TIMESTAMP NULL,
  `created` TIMESTAMP NULL,
  `timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `last_login` TIMESTAMP NULL,
  `token` VARCHAR(45) NULL,
  `token_created` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PurpleDatabase`.`account_log`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PurpleDatabase`.`account_log` ;

CREATE TABLE IF NOT EXISTS `PurpleDatabase`.`account_log` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `account_id` INT NOT NULL,
  `log` TEXT NULL,
  `timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `account_id_id1` (`account_id` ASC),
  CONSTRAINT `account_log_1`
    FOREIGN KEY (`account_id`)
    REFERENCES `PurpleDatabase`.`account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PurpleDatabase`.`account_warnings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PurpleDatabase`.`account_warnings` ;

CREATE TABLE IF NOT EXISTS `PurpleDatabase`.`account_warnings` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `account_id` INT NOT NULL,
  `warning_level` INT NOT NULL DEFAULT 1,
  `log` TEXT NULL,
  `timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `account_id_id2` (`account_id` ASC),
  CONSTRAINT `account_warnings_1`
    FOREIGN KEY (`account_id`)
    REFERENCES `PurpleDatabase`.`account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
