-- MySQL Script generated by MySQL Workbench
-- Fri Mar  6 22:43:40 2015
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema PurpleDatabase
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `PurpleDatabase` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `PurpleDatabase` ;

-- -----------------------------------------------------
-- Table `PurpleDatabase`.`account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PurpleDatabase`.`account` ;

CREATE TABLE IF NOT EXISTS `PurpleDatabase`.`account` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'Main user account',
  `GUID` VARCHAR(45) NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(60) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `email_verification` TIMESTAMP NULL,
  `account_created` TIMESTAMP NULL,
  `timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `gender` ENUM('male', 'female') NULL,
  `birthday` DATE NULL,
  `country_code` VARCHAR(5) NULL,
  `language_code` VARCHAR(6) NULL,
  `last_seen` TIMESTAMP NULL COMMENT 'Table for User Accounts',
  `last_login` TIMESTAMP NULL,
  `last_login_ip` VARCHAR(45) NULL,
  `account_type` ENUM('User', 'Moderator', 'GameMaster', 'Monitoring') NOT NULL DEFAULT 'User',
  `token` VARCHAR(45) NULL,
  `token_created` TIMESTAMP NULL,
  `comment` TEXT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
