-- MySQL Script generated by MySQL Workbench
-- Mon May 25 19:31:24 2015
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema PurpleDatabase
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `PurpleDatabase` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `PurpleDatabase` ;

-- -----------------------------------------------------
-- Table `PurpleDatabase`.`server_log`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PurpleDatabase`.`server_log` ;

CREATE TABLE IF NOT EXISTS `PurpleDatabase`.`server_log` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `server_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `host` VARCHAR(45) NULL,
  `port` INT NULL,
  `max_player` INT NULL,
  `type` ENUM('Account', 'Lobby', 'Game', 'Multi', 'Monitoring') NOT NULL DEFAULT 'Multi',
  `local_ip` VARCHAR(45) NULL,
  `global_ip` VARCHAR(45) NULL,
  `comment` TEXT NULL,
  `timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `server_id_id1` (`server_id` ASC),
  CONSTRAINT `server_id_1`
    FOREIGN KEY (`server_id`)
    REFERENCES `PurpleDatabase`.`server` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
