-- MySQL Script generated by MySQL Workbench
-- Thu Mar 26 19:11:27 2015
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema PurpleDatabase
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `PurpleDatabase` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `PurpleDatabase` ;

-- -----------------------------------------------------
-- Table `PurpleDatabase`.`account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PurpleDatabase`.`account` ;

CREATE TABLE IF NOT EXISTS `PurpleDatabase`.`account` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'Main user account',
  `guid` VARCHAR(45) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` TEXT NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `email_verification` TIMESTAMP NULL,
  `account_created` TIMESTAMP NULL,
  `timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `gender` ENUM('male', 'female') NULL,
  `birthday` DATE NULL,
  `country_code` VARCHAR(5) NULL,
  `language_code` VARCHAR(6) NULL,
  `last_seen` TIMESTAMP NULL COMMENT 'Table for User Accounts',
  `last_login` TIMESTAMP NULL,
  `last_login_ip` VARCHAR(45) NULL,
  `account_type` ENUM('User', 'Moderator', 'GameMaster', 'Monitoring') NOT NULL DEFAULT 'User',
  `token` VARCHAR(45) NULL,
  `token_created` TIMESTAMP NULL,
  `comment` TEXT NULL,
  `active` TINYINT(1) NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  UNIQUE INDEX `guid_UNIQUE` (`guid` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `PurpleDatabase`.`account`
-- -----------------------------------------------------
START TRANSACTION;
USE `PurpleDatabase`;
INSERT INTO `PurpleDatabase`.`account` (`id`, `guid`, `username`, `password`, `email`, `email_verification`, `account_created`, `timestamp`, `first_name`, `last_name`, `gender`, `birthday`, `country_code`, `language_code`, `last_seen`, `last_login`, `last_login_ip`, `account_type`, `token`, `token_created`, `comment`, `active`) VALUES (1, '1c78871f-d60c-4be5-9a7a-fc1cfc2feeaf', 'administrator', '1000:qyxoPLbY1ITSWuM6KMLq+dVXqKp2Wetm:kYtlS2zEri+dqMKGh9Q8M7/hM0k/bYSj', 'admin@localhost', '2015-03-08 09:45:45', '2015-03-08 09:45:45', '2015-03-08 09:45:45', 'Purple', 'Admin', 'male', '1984-02-24', 'de', 'de', '2015-03-08 09:45:45', '2015-03-08 09:45:45', '127.0.0.1', 'GameMaster', NULL, NULL, 'Password: PurplePassword', 1);

COMMIT;

